<?php

namespace App\Http\Helper;

/**
 * Mapped array from https://www.onixs.biz/fix-dictionary/4.4/app_6_c.html
 * Class ExchangeNameHelper
 * @package App\Http\Helper
 */
class ExchangeNameHelper
{
    public const MIC_TO_OLD_FIX_42_VALUE = [
        'DSMD' => 'QA',
        'IEPA' => '48',
        'PINX' => 'PNK',
        'THRD' => 'TH',
        'TRWB' => '30',
        'XAEX' => 'E',
        'XABJ' => 'CI',
        'XAMM' => 'AM',
        'XAMS' => 'AS',
        'XASE' => 'A',
        'XASX' => 'AX',
        'XBAH' => 'BH',
        'XBAR' => 'BC',
        'XBER' => 'BE',
        'XBEY' => 'BY',
        'XBFO' => 'B',
        'XBIL' => 'BI',
        'XBKK' => 'BK',
        'XBOM' => 'BO',
        'XBOS' => 'B',
        'XBOT' => 'BT',
        'XBRE' => 'BM',
        'XBRN' => 'BN',
        'XBRU' => 'BR',
        'XBSP' => 'SA',
        'XCAL' => 'CL',
        'XCBO' => 'W',
        'XCFV' => 'EB',
        'XCHI' => 'MW',
        'XCIE' => 'CH',
        'XCIS' => 'C',
        'XCME' => '2',
        'XCOL' => 'CM',
        'XCSE' => 'CO',
        'XCVM' => 'IN',
        'XDES' => 'DL',
        'XDFM' => 'DU',
        'XDUB' => 'I',
        'XDUS' => 'D',
        'XEUR' => 'd',
        'XFKA' => 'FU',
        'XFMN' => 'LN',
        'XFRA' => 'F',
        'XGHA' => 'GH',
        'XHAM' => 'H',
        'XHAN' => 'HA',
        'XHEL' => 'HE',
        'XHKG' => 'HK',
        'XICE' => 'IC',
        'XISM' => '15',
        'XIST' => 'IS',
        'XISX' => 'Y',
        'XJAS' => ['Q', 'QJ'],
        'XJKT' => 'JK',
        'XJSE' => 'J',
        'XJWY' => '14',
        'XKAR' => 'KA',
        'XKAZ' => 'KZ',
        'XKLS' => 'KL',
        'XKOR' => ['KS', 'KQ'],
        'XKUW' => 'KW',
        'XKYO' => 'KY',
        'XLIF' => '3',
        'XLIM' => 'LM',
        'XLIS' => 'LS',
        'XLIT' => 'VL',
        'XLON' => 'L',
        'XLTO' => '5',
        'XLUS' => 'LZ',
        'XLUX' => 'LU',
        'XMAD' => 'MA',
        'XMAL' => 'MT',
        'XMAU' => 'MZ',
        'XMDS' => 'MD',
        'XMED' => 'ML',
        'XMEX' => 'MX',
        'XMIC' => 'MM',
        'XMIL' => 'MI',
        'XMON' => 'p',
        'XMOO' => ['6', 'M'],
        'XMOS' => 'MO',
        'XMRV' => '16',
        'XMUN' => 'MU',
        'XMUS' => 'OM',
        'XNAI' => 'NR',
        'XNAM' => 'NM',
        'XNAS' => 'O',
        'XNEW' => 'NW',
        'XNGO' => 'NG',
        'XNSA' => 'LG',
        'XNSE' => 'NS',
        'XNYM' => '12',
        'XNYS' => 'N',
        'XNZE' => 'NZ',
        'XOSE' => 'OS',
        'XOSL' => 'OL',
        'XOTC' => 'OB',
        'XPAR' => 'PA',
        'XPET' => 'PE',
        'XPHL' => 'PH',
        'XPHO' => 'X',
        'XPHS' => 'PS',
        'XPRA' => 'PR',
        'XPSE' => ['P', '8'],
        'XRAS' => 'RQ',
        'XRIS' => 'RI',
        'XRUS' => 'RTS',
        'XSAP' => 'SP',
        'XSAU' => 'SE',
        'XSES' => 'SI',
        'XSFX' => 'Z',
        'XSGO' => 'SN',
        'XSHE' => 'SZ',
        'XSHG' => 'SS',
        'XSOM' => 'SO',
        'XSSE' => 'ST',
        'XSTU' => 'SG',
        'XSUR' => 'SU',
        'XSWX' => 'S',
        'XTAE' => 'TA',
        'XTAI' => ['TW', 'TWO'],
        'XTAL' => 'TL',
        'XTFN' => 'TP',
        'XTKS' => 'T',
        'XTOE' => 'K',
        'XTSE' => 'TO',
        'XTUN' => 'TN',
        'XUKR' => 'PFT',
        'XVAL' => 'VA',
        'XVSE' => 'V',
        'XVTX' => 'VX',
        'XZIM' => 'ZI',
    ];
}

